### ISSUE TITLE
启动报错 ResourceBusy

### ISSUE THREAD

**Issue by Glide01** [gfreezy/seeker#162]
系统: Mac 12.6.5
错误信息
```
sudo /Users/okay/seeker/target/release/seeker --config /Users/okay/Downloads/seeker.yml
Starting....thread 'main' panicked at 'run nat: Os { code: 16, kind: ResourceBusy, message: "Resource busy" }', seeker/src/proxy_client.rs:58:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
配置文件
```
verbose: false
dns_start_ip: 11.0.0.10
dns_servers:  # dns 服务器列表，如果不设置，会自动从系统获取。最好指定，否则 Wi-Fi 切换时可能会出现问题。
  - 127.0.0.1:1053
dns_timeout: 1s
# redir 模式使用 iptable 的 redirect 功能： iptables -t nat -A PREROUTING -d 11.0.0.0/16 -p tcp -j REDIRECT --to-ports 1300
# redir 模式下只支持 tcp 流量。默认使用 tun 模式。特殊设备不支持 tun 的情况，可以使用 redir 模式。
redir_mode: false
tun_bypass_direct: false  # 直连的域名直接返回真实IP，不走tun
tun_name: utun4
tun_ip: 11.0.0.1
tun_cidr: 11.0.0.0/16
dns_listen: 0.0.0.0:53
gateway_mode: false
probe_timeout: 200ms
ping_timeout: 2s
connect_timeout: 2s
read_timeout: 300s
write_timeout: 300s
max_connect_errors: 2
geo_ip: /Users/okay/Downloads/geoip.mmdb # geoip 数据库路径，如果使用相对路径，相对于可执行文件的路径。默认会搜索可执行文件同级目录下的 geoip.mmdb 文件
ping_urls:
  - host: www.facebook.com
    port: 80
    path: /
  - host: www.youtube.com
    port: 80
    path: /
  - host: twitter.com
    port: 80
    path: /

# remote_config_urls:  # ss 订阅地址，启动时自动拉群配置，并将配置的服务器地址自动加入服务器列表
#   - https://addr-to-ss-subscribe-url.com

servers:
  - name: a
    addr: 127.0.0.1:10380
    protocol: Socks5

rules:
  - 'IP-CIDR,21.92.33.52/32,DIRECT'
  - 'IP-CIDR,43.71.45.82/32,DIRECT'
  - 'DOMAIN,audio-ssl.itunes.apple.com,DIRECT'
  - 'DOMAIN,gspe1-ssl.ls.apple.com,REJECT'
  - 'DOMAIN-SUFFIX,aaplimg.com,DIRECT'
  - 'DOMAIN-SUFFIX,apple.co,DIRECT'
  - 'DOMAIN-KEYWORD,bbcfmt,PROXY'
  - 'DOMAIN-KEYWORD,uk-live,PROXY'
  - 'DOMAIN-SUFFIX,snssdk.com,DIRECT'
  - 'DOMAIN-SUFFIX,toutiao.com,PROBE'
  - 'GEOIP,CN,DIRECT'
  - 'MATCH,PROXY'

```
